version: '3.4'

services:
  freakyfashion.webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5100:80"

  catalogapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5200:80"

