version: '3.4'

services:

  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest

  freakyfashion.webmvc:
    image: ${DOCKER_REGISTRY-}freakyfashionwebmvc
    build:
      context: .
      dockerfile: src/Web Apps/FreakyFashion.WebMVC/Dockerfile

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog API/Dockerfile
